### ISSUE TITLE
Colum Checkbox has a bug

### ISSUE THREAD

**Issue by lostluna1** [w-ahmad/WinUI.TableView#61]
### Description:
when i clicked the button and release in 1 second, you can see it, it not work

```css
<table:TableView
    x:Name="OrderDataGrid"
    Height="700"
    Margin="0,18,0,0"
    AutoGenerateColumns="False"
    IsReadOnly="True"
    ItemsSource="{x:Bind Path=ViewModel.Orders, Mode=OneWay}"
    SelectedItem="{x:Bind Path=ViewModel.SelectedOrder, Mode=TwoWay}"
    SelectionMode="Multiple"
    SelectionUnit="Row">
``` 

### Screenshots:
![image](https://github.com/user-attachments/assets/634d6417-713a-44e5-b077-dc3887733a7e)

### Environment:
 - Package Version:
 - WinAppSDK Version:
